channels:
- conda-forge
dependencies:
- python=3.10.17
- pip<=25.1.1
- pip:
  - mlflow==2.22.0
  - cffi==1.17.1
  - cloudpickle==3.1.1
  - imbalanced-learn==0.13.0
  - lightgbm==4.6.0
  - matplotlib==3.10.3
  - numpy==2.2.5
  - pandas==2.2.3
  - psutil==7.0.0
  - pyarrow==19.0.1
  - pytest==8.3.5
  - scikit-learn==1.6.1
  - scipy==1.15.3
name: mlflow-env
