name: Build / Test / Upload to Hub

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_COLOR: "1" # Make tools pretty
  PYTHONUNBUFFERED: "1"
  PYTHON_LATEST: "3.10"

jobs:
  job-1:
    name: 'Run Tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{env.PYTHON_LATEST}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_LATEST}}

      - name: Install Poetry
        run: python3 -m pip install --upgrade poetry

      - name: Install dependencies
        run: poetry install --with dev --no-root

      - name: Run Tests
        id: test_step
        run: poetry run pytest "${{github.workspace}}/src/tests/"
        if: always()

  job-2:
    name: 'Build App Container and deploy to hub'
    runs-on: ubuntu-latest
    needs:
      - job-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mlapp:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlapp:latest
